#!groovy

// Generated by IBM TransformationAdvisor
// Fri Mar 15 20:23:02 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}