#!groovy

// Generated by IBM TransformationAdvisor
// Sat Mar 16 09:27:41 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}